# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('response', markdownx.models.MarkdownxField()),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
