# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 05:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import markdownx.models
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited', models.DateField(auto_now=True)),
                ('title', models.CharField(default=questions.models.FailureThread.title_default, max_length=50)),
                ('response', models.CharField(default=questions.models.FailureThread.response_default, max_length=50)),
            ],
            options={
                'ordering': ['last_edited', 'title'],
                'abstract': False,
                'get_latest_by': 'last_edited',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('response', markdownx.models.MarkdownxField()),
                ('last_edited', models.DateField(auto_now=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_edited', 'title'],
                'abstract': False,
                'get_latest_by': 'last_edited',
            },
        ),
    ]
