# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160818_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
