# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:00
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_thread_last_edited'),
    ]

    operations = [
        TrigramExtension()
    ]
